CREATE DATABASE MRP;
USE MRP;

CREATE TABLE PRODUCTO(
ID_PRODUCTO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOMBRE NVARCHAR(20) NOT NULL,
DESCRIPCION NVARCHAR(150) NOT NULL,
TIEMPO_ENTREGA FLOAT NOT NULL,
LOTE INT NOT NULL,
ESTADO BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE COMPOSICION(
ID_COMPOSICION INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
PRODUCTO_PRINCIPAL INT UNSIGNED NOT NULL,
FOREIGN KEY (PRODUCTO_PRINCIPAL) REFERENCES PRODUCTO(ID_PRODUCTO),
PRODUCTO_SECUNDARIO INT UNSIGNED NOT NULL,
FOREIGN KEY (PRODUCTO_SECUNDARIO) REFERENCES PRODUCTO(ID_PRODUCTO),
CANTIDAD FLOAT NOT NULL,
ESTADO BOOLEAN DEFAULT TRUE NOT NULL
);


/* PRODUCTOS A, B, C, D, E, F */
INSERT INTO `MRP`.`PRODUCTO` (`NOMBRE`,`DESCRIPCION`,`TIEMPO_ENTREGA`,`LOTE`) 
VALUES ('A', 'PRODUCTO A', 2, 0);
INSERT INTO `MRP`.`PRODUCTO` (`NOMBRE`,`DESCRIPCION`,`TIEMPO_ENTREGA`,`LOTE`) 
VALUES ('B', 'PRODUCTO B', 1, 0);
INSERT INTO `MRP`.`PRODUCTO` (`NOMBRE`,`DESCRIPCION`,`TIEMPO_ENTREGA`,`LOTE`) 
VALUES ('C', 'PRODUCTO C', 1, 0);
INSERT INTO `MRP`.`PRODUCTO` (`NOMBRE`,`DESCRIPCION`,`TIEMPO_ENTREGA`,`LOTE`) 
VALUES ('D', 'PRODUCTO D', 2, 0);
INSERT INTO `MRP`.`PRODUCTO` (`NOMBRE`,`DESCRIPCION`,`TIEMPO_ENTREGA`,`LOTE`) 
VALUES ('E', 'PRODUCTO E', 1, 0);
INSERT INTO `MRP`.`PRODUCTO` (`NOMBRE`,`DESCRIPCION`,`TIEMPO_ENTREGA`,`LOTE`) 
VALUES ('F', 'PRODUCTO F', 1, 0);

/* A */
INSERT INTO `MRP`.`COMPOSICION` (`PRODUCTO_PRINCIPAL`,`PRODUCTO_SECUNDARIO`,`CANTIDAD`)
VALUES (1,2,3);
INSERT INTO `MRP`.`COMPOSICION` (`PRODUCTO_PRINCIPAL`,`PRODUCTO_SECUNDARIO`,`CANTIDAD`)
VALUES (1,3,1);
INSERT INTO `MRP`.`COMPOSICION` (`PRODUCTO_PRINCIPAL`,`PRODUCTO_SECUNDARIO`,`CANTIDAD`)
VALUES (1,4,2);

/* B */
INSERT INTO `MRP`.`COMPOSICION` (`PRODUCTO_PRINCIPAL`,`PRODUCTO_SECUNDARIO`,`CANTIDAD`)
VALUES (2,4,1);
INSERT INTO `MRP`.`COMPOSICION` (`PRODUCTO_PRINCIPAL`,`PRODUCTO_SECUNDARIO`,`CANTIDAD`)
VALUES (2,5,2);

/* C */
INSERT INTO `MRP`.`COMPOSICION` (`PRODUCTO_PRINCIPAL`,`PRODUCTO_SECUNDARIO`,`CANTIDAD`)
VALUES (3,2,1);
INSERT INTO `MRP`.`COMPOSICION` (`PRODUCTO_PRINCIPAL`,`PRODUCTO_SECUNDARIO`,`CANTIDAD`)
VALUES (3,5,2);

/* D */

/* E */
INSERT INTO `MRP`.`COMPOSICION` (`PRODUCTO_PRINCIPAL`,`PRODUCTO_SECUNDARIO`,`CANTIDAD`)
VALUES (5,6,1);


CREATE VIEW COMPOSICIONV AS (
SELECT C.ID_COMPOSICION, P.NOMBRE AS 'PRINCIPAL', PP.NOMBRE AS 'SECUNDARIO', 
P.ID_PRODUCTO AS 'ID_PRINCIPAL', PP.ID_PRODUCTO AS 'ID_SECUNDARIO'
FROM COMPOSICION C
INNER JOIN PRODUCTO P
ON C.PRODUCTO_PRINCIPAL = P.ID_PRODUCTO 
INNER JOIN PRODUCTO PP
ON C.PRODUCTO_SECUNDARIO = PP.ID_PRODUCTO
);

